Kasino:

<Kasino>:
    GridLayout:
        cols: 1
        rows: 9
        GridLayout:
            cols: 3
            rows: 1
            Label:
                id: schwer
                text: ""
            Label:
                id: geld1
                text: "Vermögen in $:" 
            Label:
                id: geld2
                text: "10000"
             
        Label:
            id: label1
            text: "Ich denke mir eine Zahl zwischen 1 und 1000"
        
        GridLayout:
            cols: 2
            rows: 2
            Label:
                id: labels1
                text: "Score:"
        
            Label:
                id: labels2
                text: "0"
            
            Label:
                id: labelh1
                text: "Highscore:"
            
            Label:
                id: labelh2
                text: "999"

        Slider:
            id: slider
            min: 1
            max: 1000
            step: 1
            value: 500
            orientation: "horizontal"
        
        Button:
            id: button1
            text: "-"
            on_press: root.button_m()
        
        Label:
            id: label2
            text: str(slider.value)
        
        Button:
            id: button2
            text: "+"
            on_press: root.button_p()
        
        Button:
            id: button3
            text: "OK"
            on_press: root.button_ok()
            
        GridLayout:
            cols:2
            rows:1
            Button:
                text: "GameOne"
                on_press: 
                    root.manager.current = "GameOne"
                    root.manager.transition.direction = "right"
            Button:
                text: "GameTwo"
                on_press: 
                    root.manager.current = "GameTwo"
                    root.manager.transition.direction = "left"
                    
<GameOne>:
    GridLayout:
        cols: 1
        rows: 9
        GridLayout:
            cols: 3
            rows: 1
            Label:
                id: schwer1
                text: ""
            Label:
                id: geld3
                text: "Vermögen in $:"
            Label:
                id: geld4
                text: "0"
        
        Label:
            text: "Klicke den Cookie"
            
        ProgressBar:
            id: bar
            max: 20
            value: 0
            
        Label:
            text: ""
            
        GridLayout:
            cols: 3
            rows: 1
            Label:
                text: ""
            Button:
                id: cookie1
                background_color: 0, 0, 0, 0
                on_press: root.button_s1()
            Label:
                text: ""
            
        GridLayout:
            cols: 3
            rows: 1
            Label:
                text: ""
            Button:
                id: cookie2
                background_color: 0, 0, 0, 0
                on_press: root.button_s1()
                Image:
                    source: "Bilder/Cookie.png"
                    center_x: self.parent.center_x
                    center_y: self.parent.center_y
                    fit_mode: "contain"
                    size: root.width * 0.4, root.height * 0.4
            Label:
                text: ""
                
        GridLayout:
            cols: 3
            rows: 1
            Label:
                text: ""
            Button:
                id: cookie3
                background_color: 0, 0, 0, 0
                on_press: root.button_s1()
            Label:
                text: ""
        
        Label:
            text: ""
            
        GridLayout:
            cols:2
            rows:1
            Button:
                text: "GameThree"
                on_press: 
                    root.manager.current = "GameThree"
                    root.manager.transition.direction = "down"
            Button:
                text: "zurück"
                on_press: 
                    root.manager.current = "Kasino"
                    root.manager.transition.direction = "left"
                    
<GameTwo>:
    GridLayout:
        cols: 1
        rows: 9
        GridLayout:
            cols: 3
            rows: 1
            Label:
                id: schwer2
                text: ""
            Label:
                id: geld5
                text: "Vermögen in $:"
            Label:
                id: geld6
                text: "0"
                
        Label:
            text: "Löse die Rechnung in der gegebenen Zeit"
            
        ProgressBar:
            id: timer1
            max: 60
            value: 0
            
        Label:
            text: ""
            
        GridLayout:
            cols: 5
            rows: 1
            Label:
                id: zahl1
                text: ""
            Label:
                id: plus
                text: "+"
            Label:
                id: zahl2
                text: ""
            Label:
                id: gleich1
                text: "="
            TextInput:
                id: ergebnis1
                text: ""
                multiline: False
                 
        Label:
            text: ""
            
        Button:
            id: starttimer1
            text: "Start"
            on_press:
                root.start_timer1()
             
        GridLayout:
            cols:2
            rows:1
            Button:
                text: "zurück"
                on_press: 
                    root.manager.current = "Kasino"
                    root.manager.transition.direction = "right"
            Button:
                text: "GameFour"
                on_press: 
                    root.manager.current = "GameFour"
                    root.manager.transition.direction = "up"
                
<GameThree>:
    GridLayout:
        cols: 1
        rows: 9
        GridLayout:
            cols: 3
            rows: 1
            Label:
                id: schwer3
                text: ""
            Label:
                id: geld7
                text: "Vermögen in $:"
            Label:
                id: geld8
                text: "0"
                
        Label:
            text: "Halte den Ladebalken zum richtigen Zeitpunkt auf"
            
        Label:
            text: ""
        
        ProgressBar:
            id: balken1
            max: 100
            value: 0
            
        ProgressBar:
            id: balken2
            max: 100
            value: 0
        
        Button:
            id: startbalken
            text: "Start"
            on_press:
                root.start_balken()
                
        Button:
            id: stoppbalken
            text: "Stopp"
            on_press:
                root.stopp_balken()
        
        Label:
            text: ""
            
        GridLayout:
            cols: 2
            rows: 1
            Button:
                text: "zurück"
                on_press: 
                    root.manager.current = "GameOne"
                    root.manager.transition.direction = "up"
            Button:
                text: "GameFive"
                on_press: 
                    root.manager.current = "GameFive"
                    root.manager.transition.direction = "left"
                    
<GameFour>:
    GridLayout:
        cols: 1
        rows: 9
        GridLayout:
            cols: 3
            rows: 1
            Label:
                id: schwer4
                text: ""
            Label:
                id: geld9
                text: "Vermögen in $:"
            Label:
                id: geld10
                text: "0"
                
        Label:
            text: "Löse die Rechnung in der gegebenen Zeit"
            
        ProgressBar:
            id: timer2
            max: 60
            value: 0
            
        Label:
            text: ""
            
        GridLayout:
            cols: 5
            rows: 1
            Label:
                id: zahl3
                text: ""
            Label:
                id: minus
                text: "-"
            Label:
                id: zahl4
                text: ""
            Label:
                id: gleich2
                text: "="
            TextInput:
                id: ergebnis2
                text: ""
                multiline: False
                 
        Label:
            text: ""
            
        Button:
            id: starttimer2
            text: "Start"
            on_press:
                root.start_timer2()
             
        GridLayout:
            cols: 2
            rows: 1
            Button:
                text: "GameSix"
                on_press: 
                    root.manager.current = "GameSix"
                    root.manager.transition.direction = "right"
            Button:
                text: "zurück"
                on_press: 
                    root.manager.current = "GameTwo"
                    root.manager.transition.direction = "down"

<GameFive>:
    GridLayout:
        cols: 1
        rows: 9
        GridLayout:
            cols: 3
            rows: 1
            Label:
                id: schwer5
                text: ""
            Label:
                id: geld11
                text: "Vermögen in $"
            Label:
                id: geld12
                text: ""
                
        Label:
            id: ttt
            text: "Besiege mich in TikTakToe"
            
        Label:
            text: ""
            
        GridLayout:
            id: grd1
            cols: 3
            rows: 1
        GridLayout:
            id: grd2
            cols: 3
            rows: 1
        GridLayout:
            id: grd3
            cols: 3
            rows: 1
    
        Label:
            text: ""
            
        Button:
            id: ng
            text: "Neues Spiel"
            on_press: root.create_ttt()
            
        GridLayout:
            cols: 2
            rows: 1
            Button:
                text: "zurück"
                on_press: 
                    root.manager.current = "GameThree"
                    root.manager.transition.direction = "right"
            Button:
                text: "GameSeven"
                on_press: 
                    root.manager.current = "GameSeven"
                    root.manager.transition.direction = "left"


<GameSix>:
    GridLayout:
        cols: 1
        rows: 9
        GridLayout:
            cols: 3
            rows: 1
            Label:
                id: schwer6
                text: ""
            Label:
                id: geld13
                text: "Vermögen in $:"
            Label:
                id: geld14
                text: "0"
                
        Label:
            text: "Löse die Rechnung in der gegebenen Zeit"
            
        ProgressBar:
            id: timer3
            max: 60
            value: 0
            
        Label:
            text: ""
            
        GridLayout:
            cols: 5
            rows: 1
            Label:
                id: zahl5
                text: ""
            Label:
                id: mal
                text: "*"
            Label:
                id: zahl6
                text: ""
            Label:
                id: gleich3
                text: "="
            TextInput:
                id: ergebnis3
                text: ""
                multiline: False
                 
        Label:
            text: ""
            
        Button:
            id: starttimer3
            text: "Start"
            on_press:
                root.start_timer3()
             
        GridLayout:
            cols: 2
            rows: 1
            Button:
                text: "GameEight"
                on_press: 
                    root.manager.current = "GameEight"
                    root.manager.transition.direction = "right"
            Button:
                text: "zurück"
                on_press: 
                    root.manager.current = "GameFour"
                    root.manager.transition.direction = "left"
                    
<GameSeven>:
    GridLayout:
        cols: 1
        rows: 9
        GridLayout:
            cols: 3
            rows: 1
            Label:
                id: schwer7
                text: ""
            Label:
                id: geld15
                text: "Vermögen in $:"
            Label:
                id: geld16
                text: ""
       
        Label:
            id: labelm
            text: "Finde Geld ohne auf Minen zu treten"
       
        GridLayout:
            id: grid1
            cols: 10
            rows: 2
        GridLayout:
            id: grid2
            cols: 10
            rows: 2
        GridLayout:
            id: grid3
            cols: 10
            rows: 2
        GridLayout:
            id: grid4
            cols: 10
            rows: 2
        GridLayout:
            id: grid5
            cols: 10
            rows: 2
            
        Button:
            id: generieren
            text: "Neues Minenfeld"
            on_press: root.create_minefield()
        
        Button:
            text: "zurück"
            on_press: 
                root.manager.current = "GameFive"
                root.manager.transition.direction = "right"
                
<GameEight>:
    GridLayout:
        cols: 1
        rows: 9
        GridLayout:
            cols: 3
            rows: 1
            Label:
                id: schwer8
                text: ""
            Label:
                id: geld17
                text: "Vermögen in $:"
            Label:
                id: geld18
                text: "0"
                
        Label:
            text: "Löse die Rechnung in der gegebenen Zeit"
            
        ProgressBar:
            id: timer4
            max: 60
            value: 0
            
        Label:
            text: ""
            
        GridLayout:
            cols: 5
            rows: 1
            Label:
                id: zahl7
                text: ""
            Label:
                id: geteilt
                text: "/"
            Label:
                id: zahl8
                text: ""
            Label:
                id: gleich4
                text: "="
            TextInput:
                id: ergebnis4
                text: ""
                multiline: False
                 
        Label:
            text: ""
            
        Button:
            id: starttimer4
            text: "Start"
            on_press:
                root.start_timer4()
             
        Button:
            text: "zurück"
            on_press: 
                root.manager.current = "GameSix"
                root.manager.transition.direction = "left"