name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Buildozer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip build-essential
          pip install cython
          pip install buildozer

      - name: Accept Android SDK Licenses and Install Build Tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "build-tools;36.1.0" "platform-tools" "platforms;android-36"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ErsteApp
          path: bin/*.apk
